default: &default
  adapter: postgresql
  encoding: unicode
  username: rails
  password: rails
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello_rails_react_dev

test:
  <<: *default
  database: hello_rails_react_test

production:
  <<: *default
  database: hello_rails_react_production
